---

- name: Add user group "{{ user.group }}"
  group: name={{ user.group }}
  become: yes
  become_user: root
  tags: user

- name: Add user "{{ user.username }}"
  user: name={{ user.username }} groups="sudo" group={{ user.group }}
  become: yes
  become_user: root
  tags: tomcat