---

- name: Add user group "{{ user.group }}"
  group: name={{ user.group }}
  become: true
  become_method: sudo
  tags: user

- name: Add user "{{ user.username }}"
  user: name={{ user.username }} groups="sudo" group={{ user.group }}
  become: true
  become_method: sudo
  tags: tomcat