---

- name: Install necessary repository
  apt: >
    name=python-software-properties
    state=latest
  become: true
  become_method: sudo
  tags: libreoffice

- name: Add repository
  apt_repository: >
    repo="{{ libreoffice.apt_repository }}-{{ libreoffice.version }}"
    state=present
    update_cache=yes
  become: true
  become_method: sudo
  tags: libreoffice

- name: Install LibreOffice {{ libreoffice.version }}
  apt: >
      name={{ item }}
      state=latest
  with_items:
      - libreoffice-writer
      - libreoffice-draw
      - libreoffice-calc
  become: true
  become_method: sudo
  tags: libreoffice